/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#490080",
        "outline": "#849495",
        "on-primary-container": "#006970",
        "inverse-surface": "#e2e2ea",
        "outline-variant": "#3b494b",
        "surface-container-lowest": "#0c0e13",
        "on-secondary-fixed-variant": "#2f3aa3",
        "on-background": "#e2e2ea",
        "tertiary": "#fdf2ff",
        "primary": "#dbfcff",
        "surface-tint": "#00dbe9",
        "surface-container": "#1d2025",
        "on-tertiary-fixed-variant": "#6900b3",
        "surface-variant": "#33353b",
        "on-primary-fixed": "#002022",
        "inverse-primary": "#006970",
        "on-primary-fixed-variant": "#004f54",
        "on-secondary-fixed": "#000767",
        "on-primary": "#00363a",
        "surface-dim": "#111319",
        "secondary-fixed-dim": "#bdc2ff",
        "on-surface": "#e2e2ea",
        "on-secondary": "#131e8c",
        "surface-container-low": "#191c21",
        "on-error": "#690005",
        "secondary-fixed": "#e0e0ff",
        "surface-container-high": "#282a30",
        "primary-fixed-dim": "#00dbe9",
        "tertiary-fixed": "#f0dbff",
        "surface-bright": "#37393f",
        "on-surface-variant": "#b9cacb",
        "error-container": "#93000a",
        "on-tertiary-fixed": "#2c0051",
        "on-error-container": "#ffdad6",
        "background": "#111319",
        "tertiary-container": "#eacfff",
        "inverse-on-surface": "#2e3036",
        "on-secondary-container": "#a8afff",
        "error": "#ffb4ab",
        "surface": "#111319",
        "on-tertiary-container": "#842bd2",
        "tertiary-fixed-dim": "#ddb7ff",
        "surface-container-highest": "#33353b",
        "secondary": "#bdc2ff",
        "secondary-container": "#2f3aa3",
        "primary-container": "#00f0ff",
        "primary-fixed": "#7df4ff",
        obsidian: {
          950: '#07080c',
          900: '#0b0d14',
          850: '#0f111a',
          800: '#151824',
          700: '#1f2438',
        },
        electric: {
          purple: '#8b5cf6',
          violet: '#7c3aed',
          cyan: '#00f0ff',
          cyanSoft: '#38bdf8',
        },
        dark: {
          950: '#07080c',
          900: '#0b0d14',
          850: '#0f111a',
          800: '#151824',
          700: '#1f2438',
        },
        brand: {
          violet: '#8B5CF6',
          indigo: '#6366F1',
          cyan: '#00F0FF',
        }
      },
      fontFamily: {
        syne: ['Syne', 'sans-serif'],
        space: ['Space Grotesk', 'sans-serif'],
        sans: ['Plus Jakarta Sans', 'Inter', 'sans-serif'],
        "display-hero": ['Space Grotesk', 'sans-serif'],
        "headline-lg": ['Space Grotesk', 'sans-serif'],
        "headline-md": ['Space Grotesk', 'sans-serif'],
        "metric-val": ['Space Grotesk', 'sans-serif'],
        "label-pill": ['Space Grotesk', 'sans-serif'],
        "body-lg": ['Plus Jakarta Sans', 'sans-serif'],
        "body-md": ['Plus Jakarta Sans', 'sans-serif'],
        "body-sm": ['Plus Jakarta Sans', 'sans-serif'],
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
      spacing: {
        "space-xs": "0.375rem",
        "space-sm": "0.75rem",
        "space-md": "1.25rem",
        "space-lg": "2rem",
        "space-xl": "3.5rem",
        "gutter": "1.5rem",
        "margin": "2rem",
      },
      aspectRatio: {
        '9/16': '9 / 16',
        '16/9': '16 / 9',
      },
      animation: {
        'pulse-slow': 'pulse 4s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'float': 'float 6s ease-in-out infinite',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-10px)' },
        }
      }
    },
  },
  plugins: [],
};
